### ISSUE TITLE
Cannot find package on node 20

### ISSUE THREAD

**Issue by kareljan** [phosphor-icons/react#88] opened 2024-04-01 15:27 UTC
**Describe the bug**

When I try to use the icons in a nextjs project on node 20.12.0 I get the following error. 

Cannot find package '/pathtoproject/node_modules/@phosphor-icons/react/dist/node_modules/.pnpm/react@18.2.0/node_modules/react/package.json'

**Steps to Reproduce**

Try using it in a node 20 react project

**Expected behavior**

No errors

**Context (please complete the following information):**

- OS: Mac OS 14.4
- @phosphor-icons/react
- Version 2.1.4

**Comment by rektdeckard** [comment] 2024-04-01 19:11
I just created a fresh React/Typescript/Vite/Node 20.12.0 project and have no issues, so I suspect this may be specific to NextJS...as usual.

Can you share a minimal reproduction I can test against? StackBlitz doesn't support Node 20 just yet, but maybe a GitHub Codespace or something? Thanks.

**Comment by KarelJanVanHaute** [comment] 2024-04-02 20:06
Hey @rektdeckard 

For now, I don't seem to get it to break in a contained environment. I guess the problem lies deeper in my code.
I'll keep you posted if I find the cause of the problem.

**Comment by KarelJanVanHaute** [comment] 2024-04-11 15:46
Hey @rektdeckard 

You can find a minimal example of the error on https://supreme-space-orbit-rq9g7q4xqx3rpv.github.dev/

**Comment by johnnyshankman** [comment] 2024-04-15 22:10
im having this issue as well. had to revert to `2.0.15`

**Comment by johnnyshankman** [comment] 2024-04-15 22:21
**Describe the bug**

When running a classic Vitest config setup, phosphor icons return errors relating to path imports, possibly due to pnpm.

**Steps to Reproduce**



Include phosphor icons in a react-vite repo. Then use vitest to test the component.

Behavior:
```
 FAIL  tests/components/z.test.ts [ tests/components/z.test.ts ]
Error: Cannot find package '/Users/xxxx/Documents/yyyyyy/studio-app-devtools/node_modules/@phosphor-icons/react/dist/node_modules/.pnpm/react@18.2.0/node_modules/react/package.json' imported from /Users/xxxx/Documents/yyyyyy/studio-app-devtools/node_modules/@phosphor-icons/react/dist/node_modules/.pnpm/react@18.2.0/node_modules/react/cjs/react-jsx-runtime.production.min.mjs
Did you mean to import react/index.js?
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
```

**Expected behavior**



Behaves like any other React component dependency and renders like it does in production and in development servers on vite.

**Screenshots**



**Context (please complete the following information):**

    "vitest": "^1.4.0",
    "vite": "^5.2.7",
    "@phosphor-icons/react": "^2.1.4",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.3.0"
    "@testing-library/react": "^14.1.2",



**Additional notes**

**Comment by rektdeckard** [comment] 2024-04-18 20:38
Identified to be same issue as #90. Closing as duplicate, but fix incoming!

**Closed by rektdeckard** 2024-04-18 20:38 UTC
Labels: bug
