### ISSUE TITLE
Error caused by `exports` field in `package.json`

### ISSUE THREAD

**Issue by milovangudelj** [phosphor-icons/react#41] opened 2023-03-08 18:28 UTC
**Describe the bug**
Using the latest version of the package (`v2.0.4`) along with esbuild and Next.js v13 this error pops up in the console when trying to import any icon from the library.

```sh
Package path . is not exported from package /my_pc_project_path/node_modules/@phosphor-icons/react (see exports field in /my_pc_project_path/node_modules/@phosphor-icons/react/package.json)
```

Looking up the path reported I can see this entry

```json-with-comments
// other stuff...
"exports": {
  ".": {
    "import": "./dist/index.es.js"
  }
},
// more stuff...
```

**To Reproduce**
It is quite the hassle, it invlolves setting up a monorepo with Turborepo and creating different apps and packages. If necessary I can provide a link to my repository.

**Expected behavior**
I expect the app to work without throwing any errors both in developement and production.

**Desktop:**
 - OS: Fedora Linux 36 (Workstation Edition)
 - Browser: Brave
 - Version: Version 1.48.164 Chromium: 110.0.5481.100 (Official Build) (64-bit)

**Comment by rektdeckard** [comment] 2023-03-09 01:40
Transferring issue to `@phosphor-icons/react`, since it pertains to this library only.

**Comment by rektdeckard** [comment] 2023-03-10 16:58
Glad to hear you got it resolved. It sounds like the issue is actually that we don't provide a CJS export anymore 😟

**Comment by milovangudelj** [comment] 2023-03-14 19:04
Out of curiosity, why is that? I mean, why don't you provide a CJS export anymore? Is it just a decision to move towards an ESM future or is there a technical issue that prevents you from being able to provide both?

**Comment by madly0894** [comment] 2023-03-25 21:09
Any solution?(

**Comment by milovangudelj** [comment] 2023-03-25 21:31
The solution rn is to convert your package type from `commonjs` to `module` in your `package.json`.

Once you do that you can then add
```json
"module": "nodenext",
```
in your `tsconfig` file. This should fix the issue.

If for some reason you can't convert to a module type package you can remove the `exports` field from the library's `package.json` present in the `node_modules` directory, but that's just a temporary fix.

**Comment by madly0894** [comment] 2023-03-26 13:12
I use js. Instead of ts config, i added in jsconfig
This solution didn't work for me(

**Comment by milovangudelj** [comment] 2023-03-26 22:59
From VS Code's `jsconfig.json` [reference page](https://code.visualstudio.com/docs/languages/jsconfig)
> Tip: `jsconfig.json` is a descendant of [tsconfig.json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html), which is a configuration file for TypeScript. `jsconfig.json` is `tsconfig.json` with `"allowJs"` attribute set to `true`.

So you should still be able to declare this in there
```json
"module": "nodenext",
```

**Comment by rylanharper** [comment] 2023-03-27 23:07
Does anyone know what the solution for this is? I am also getting this issue when using Phosphor Icons with [Sanity](https://www.sanity.io/)

**Comment by milovangudelj** [comment] 2023-03-27 23:36
Nope, it goes either in your `tsconfig.json` or `jsconfig.json` file.

This is necessary if you're trying to use an ESM-only package, and `@phosphor-icons/react` became ESM-only after v2.

**Comment by milovangudelj** [comment] 2023-03-27 23:59
As I mentioned above that only works if you have set your package type to `"module"` instead of `"commonjs"` in your `package.json` file.

But this isn't possible for every type of application/package. Sanity requires you to use common js and switching is quite the hassle. I've tried doing that in the past with various degrees of success and you have to make compromises whichever way you chose to go.

**Comment by rektdeckard** [comment] 2023-04-02 07:04
I've just published v2.0.7, which includes a UMD export (compatible with CJS build tooling), and does not specify `"type": "module"` in `package.json`. This *should* alleviate all of the build issues mentioned here. As a side-effect of the build, we won't support any qualified imports in that environment:

```ts
import AddressBook from "@phosphor-icons/react/AddressBook"; // CAN'T DO THIS IN CJS ENVIRONMENT
import { AddressBook } from "@phosphor-icons/react"; // CAN DO THIS IN EITHER ENVIRONMENT
```

**Comment by rektdeckard** [comment] 2023-04-02 16:56
I also recommend using the fully qualified path if you're doing modular imports (@phosphor-icons/react/dist/icons/Foo)

**Comment by rylanharper** [comment] 2023-04-03 19:51
@rektdeckard I just testing the latest update of `@phosphor-icons/react` with Sanity (latest version `3.8.2`) and its working great! No issues are logged when deploying graphql or with importing icons into react templates!

**Comment by rektdeckard** [comment] 2023-04-04 17:48
Any other issues here, or safe to close?

**Comment by rylanharper** [comment] 2023-04-04 17:56
Everything is all good for me. Seems like the original issue is resolved as well @milovangudelj?

**Comment by milovangudelj** [comment] 2023-04-04 18:51
I haven't had the chance to try it out yet but judging from what I've read so far it seems resolved. I'll close the issue for now.

Feel free to reopen it if you find more errors related to this.

**Closed** 2023-04-04 18:51 UTC
Labels: bug
